#!/bin/bash

####run as: addqueue -s -n 1x1 -m 4 -q berg2 ./jobscript
### can use berg, berg2 and cmb queues
### output to /mnt/extraspace/kclough

module load gcc/5.4.0 intel-compilers/18 hdf5/1.8.13-intel15 mpi/3.2-intel15
export OMP_NUM_THREADS=1
/usr/local/shared/slurm/bin/srun -n 1 -m cyclic --mpi=pmi2 Main_ScalarField3d.Linux.64.mpicxx.ifort.DEBUG.OPT.MPI.OPENMPCC.ex params.txt
